version: "3.8"

configs:
  environment:
    - NEXTCLOUD_POSTGRES_DB: ${NEXTCLOUD_POSTGRES_DB:-nextcloud}
    - NEXTCLOUD_POSTGRES_USER: ${NEXTCLOUD_POSTGRES_USER:-nextcloud}
    - NEXTCLOUD_POSTGRES_PASSWORD: ${NEXTCLOUD_POSTGRES_PASSWORD:?Missing NEXTCLOUD_POSTGRES_PASSWORD}
    - NEXTCLOUD_POSTGRES_PATH: ${NEXTCLOUD_POSTGRES_PATH:?Missing NEXTCLOUD_POSTGRES_PATH}
    - NEXTCLOUD_DOMAIN: ${NEXTCLOUD_DOMAIN:?Missing NEXTCLOUD_DOMAIN}
    - NEXTCLOUD_PROTOCOL: ${NEXTCLOUD_PROTOCOL:-https}
    - NEXTCLOUD_PORT: ${NEXTCLOUD_PORT:-80}
    - NEXTCLOUD_PATH: ${NEXTCLOUD_PATH?Missing NEXTCLOUD_PATH}
    - NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER?Missing NEXTCLOUD_ADMIN_USER}
    - NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD?Missing NEXTCLOUD_ADMIN_PASSWORD}

services:
  postgres:
    image: docker.io/library/postgres
    environment:
      PGUSER: $NEXTCLOUD_POSTGRES_USER
      POSTGRES_DB: $NEXTCLOUD_POSTGRES_DB
      POSTGRES_PASSWORD: $NEXTCLOUD_POSTGRES_PASSWORD
      POSTGRES_USER: $NEXTCLOUD_POSTGRES_USER
    restart: always
    network_mode: bridge
    volumes:
      - $NEXTCLOUD_POSTGRES_PATH:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextcloud:
    image: docker.io/library/nextcloud
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: $NEXTCLOUD_DOMAIN
      OVERWRITECLIURL: "$NEXTCLOUD_PROTOCOL://$NEXTCLOUD_DOMAIN"
      OVERWRITEPROTOCOL: $NEXTCLOUD_PROTOCOL
      POSTGRES_DB: $NEXTCLOUD_POSTGRES_DB
      POSTGRES_HOST: "postgres"
      POSTGRES_PASSWORD: $NEXTCLOUD_POSTGRES_PASSWORD
      POSTGRES_USER: $NEXTCLOUD_POSTGRES_USER
      NEXTCLOUD_ADMIN_USER: $NEXTCLOUD_ADMIN_USER
      NEXTCLOUD_ADMIN_PASSWORD: $NEXTCLOUD_ADMIN_PASSWORD
    restart: always
    network_mode: bridge
    ports:
      - $NEXTCLOUD_PORT:80
    volumes:
      - $NEXTCLOUD_PATH/data:/var/www/html/data
      - $NEXTCLOUD_PATH/config:/var/www/html/config
    depends_on:
      postgres:
        condition: service_healthy
