version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8081:81'
      - '8443:443'
    volumes:
      - /home/shadows/nginx/data:/data
      - /home/shadows/nginx/letsencrypt:/etc/letsencrypt
    # network_mode: "host"

